### PR TITLE
Extract tomogram 

### PR DESCRIPTION
**Pull request by adrianq**
This protocol depends on https://github.com/scipion-em/scipion-em-tomo/pull/4

### CODE REVIEW

**Comment by delarosatrevin** [comment]
I see one possible issue here...if we add V2.3 as supported Eman2 version...then all the existing protocols for SPA should be working with this version as well (or at least those that make sense).

**Comment by adrianq** [comment]
Yes, I agree 100% but we don't have all the tomo features in V2.21 so I prefer to work with a single version where everything is working as expected. As this PR is targeting the tomo branch (not devel), my idea was to, little by little, check (or adapt) all protocols to V2.3 in the tomo branch. Then merge this branch into devel once everything is stable and works as expected.

**Comment by delarosatrevin** [comment]
Yep, I think it is a good idea to focus tomo development of Eman in this version if it is the one that fully supports it. So, I will merge this PR and we should keep this in mind when merging the 'tomo' branch to 'devel'.

**Comment by delarosatrevin** [comment]
Wait, maybe one test for the new extraction protocol?

**Comment by azazellochg** [comment]
eman2.3 is in devel! :)

**Comment by adrianq** [comment]
@delarosatrevin I have added a few tests for the different protocols and I have just merged with the latest dev (thanks @azazellochg) that is already prepared for eman 2.3

**Pull request merged**
