### PR TITLE
Feature/multi reference

### PR DESCRIPTION
**Pull request by adrianq**
This PR will not work until https://github.com/cryoem/eman2/commit/2f0590d168d1e2ebd497c78a76dd47db5ef91961#diff-4e8bace2097bc0fe3eef18483efa589b is released. It went neither on 2.30 nor 2.31. We will have to wait for the next release.

### CODE REVIEW

**Comment by pconesa** [comment]
What is the status of this. Can this be closed now?

**Comment by adrianq** [comment]
No really. I was waiting for eman to release the fix of a particular bug in this protocol. I will take care of merging this PR with the latest and resolving any conflict

**Comment by pconesa** [comment]
Eman is migrating to python 3. they are not actively patching eman2.3. @DavidHerreros has managed to install "eman-devel" that has fixes for tomo protocols. I'd suggest to test your code against eman-devel and see.

**Comment by azazellochg** [comment]
This PR should go to eman tomo repo now.

**Pull request closed without merging**
