### PR TITLE
Use importFromPlugin for tomo protocols and remove try/catch

### LINKED ISSUE #42: Using importFromPlugin() for tomo.
Scipion has a [function to import python objects from other plugins](https://github.com/I2PC/scipion/blob/d1a60f69960d1079bbbecde5bf3f5f4017b36927/pyworkflow/utils/utils.py#L772-L788). This functions skips the error raising when plugin is not found and [gives a common hint](https://github.com/I2PC/scipion/blob/d1a60f69960d1079bbbecde5bf3f5f4017b36927/pyworkflow/utils/utils.py#L732-L769) to help user how to solve the dependency.

I suggest to import the eman-tomo protocols without the try in the [protocols/__init__.py](https://github.com/scipion-em/scipion-em-eman2/blob/b99c87ef5675dbf681cc1d0d0d7dc7293371fcb5/eman2/protocols/__init__.py#L39-L48) and import the `scipion-em-tomo`'s objects using the that functions. For instance, for the [protocol_tomo_boxing](https://github.com/scipion-em/scipion-em-eman2/blob/b99c87ef5675dbf681cc1d0d0d7dc7293371fcb5/eman2/protocols/protocol_tomo_boxing.py#L37-L38) I would import as follow
```
from pyworkflow.utils import importFromPlugin
ProtTomoPicking = importFromPlugin("tomo.protocols", "ProtTomoPicking", errorMsg=tomoNeededMsg)
SetOfCoordinates3D = importFromPlugin("tomo.objects", "SetOfCoordinates3D", errorMsg=tomoNeededMsg)
```
where
```
tomoNeededMsg='To use a Tomography protocol scipion-em-tomo plugin is required.' 
              ' See https://github.com/scipion-em/scipion-em-tomo for further details'
```
is a common message defined in constants or wherever.

Alternatively, if this solutions seems tedious, it can be done in the init.py at once but using the `pluginNotFound()` function in order to print the Scipion's hint of how to install plugins
```
try:
    from protocol_tomo_boxing import EmanProtTomoBoxing
    ....
except ImportError:
    from pyworkflow.utils import pluginNotFound
    pluginNotFound("tomo", errorMsg='To use a Tomography protocol scipion-em-tomo plugin is required.'
                                    ' See https://github.com/scipion-em/scipion-em-tomo for further details')
```

In addition, I would not raise an error in any case in order to prevent make eman inaccessible for those users that hasn't scipion-em-tomo installed.

### PR DESCRIPTION
**Pull request by adrianq**
Closes #42

### CODE REVIEW

**Comment by EstrellaFG** [comment]
@adrianq so the try-catch is no longer necessary in the init? I understood from @dmaluenda that I should leave it in scipion-em-xmipp even if the "importFromPlugin" function is being used in the protocols, but maybe I missunderstood it and the try in the init is not longer needed.

**Comment by adrianq** [comment]
@EstrellaFG I understood exactly the opposite ;) Can you please give it a try deleting the tomo plugin and let me know if it works without the try/catch?

**Comment by dmaluenda** [comment]
Ok. The best option is what @adrianq have done.

`protocols/__init__.py` should only contains internal protocols (this is protocols of its own plugin, not external ones). Whereas in any certain protocol, you can call for external protocols or objects from other plugins by using `importFromPlugin()` function (without try/catch).

In Xmipp plugin, some tomo dependencies are called in the `protocols/__init__.py`, I don't agree that, but I should think more about it bc I assume that are needed by several protocols.

Regarding the use of try/catch or not, depends. If you want to import a single, or a few things, from another plugin you don't need the try/catch and it's as follow (best option)
```
myDependency = importFromPlugin('tomo.whatever', 'myDependency')
```
since importFromPlugin() has an internal try/catch.

Whereas if you want to import quite a lot of thing, you can do the following (quick and dirty option)
```
try:
   from tomo.wherevere1 import myDependency1
   from tomo.wherevere2 import myDependency2, myDependency3
   from tomo.wherevere3 import myDependency4, myDependency5, myDependecy6
except ImportError as exc:
  pluginNotFound('tomo', exc)
```
in this case, pluginNotFound only introduce a common message and it doesn't have an internat try/catch, so you need to put it.

**Comment by EstrellaFG** [comment]
@adrianq I have tried with scipion-em-tomo plugin **un**installed and it works properly returning the error message.

**Comment by dmaluenda** [comment]
I have been testing options and I've changed of mind....

The point is that as it is in this PR and I suggested, Eman protocols cannot be load if tomo is not installed. The reason is because some protocols inherit from a tomo protocol and if it's not there, importFromPlugin() returns None. Obviously, this raise an error and the whole `eman2.protocols__init__py` fails due to now the failed protocol is not in a try/catch....

In Xmipp, we will put all tomo related protocols in a single module `xmipp3.protocols.tomo` and in the `xmipp3/protocols/__init__.py` we will import it in a try/catch statement. Something like I simulated in [this commit from dm_tomoImport branch](https://github.com/scipion-em/scipion-em-eman2/commit/09c789c77a2bc1fd3aeca05e3b08729c31e0648a).

Feel free to follow this or to leave it as it is before this PR.

Sorry for the erratic instructions from day to day ;-p

**Comment by adrianq** [comment]
@dmaluenda I have gone for an intermediate solution so to say. I have cherry-picked your commit and modified it slightly. On the other hand, I have kept the importFromPlugin approach for some methods in the convert and dataimport files. I have also unified the error message by using a constant as you suggested.

No worries about the back and forth with this protocol. I think this discussion was needed and it looks much better and elegant this way. I am merging now but feel free to drop a comment if something doesn't make too much sense for you.

**Comment by dmaluenda** [comment]
Great! I see. I thing this is the best solution, so far ;-p

For puntual imports, using the importFromPlugin function (plus the constant message). Whereas for a whole collection of protocols, making a submodule and importing it in a try/catch. Good!

Just to inform, I've actualized the importFromPlugin funtion in order to be able to import multiples objects from a certain module in order to avoid multiple lines doing almost the same. I think it will be released in the next version.

**Pull request merged**
